### ISSUE TITLE
dbt Hub link in README is broken

### ISSUE THREAD

**Issue by jordan8037310** [sgoley/dbt-postgres-utils#4]
Should link to https://hub.getdbt.com/

**Comment by sgoley** [comment]
Hey Jordan! Appreciate the link update - I had actually been waiting for the hub to be re-published with my particular link so I'm going to make that small substitution to here: https://hub.getdbt.com/sgoley/postgres_utils/latest/

Thanks for bringing up the change though! Really appreciate it.
